### PR TITLE
Make the page title appear before the site title in the HTML page title

### PR DESCRIPTION
**Pull request by michelle-rago**
The page title should appear before the site title in the HTML page title. For example, for the About page, the HTML page title should be "About federal website standards | Federal website standards."

@caleywoods I'm not sure where or how (else) to make this change.

### CODE REVIEW

**Review by caleywoods — APPROVED** [review]
This is the correct fix! I noticed the homepage doesn't have a title so it ends up getting " | Federal website standards" as its title. I can fix that if you want. It'll be something like:

```liquid
{% if permalink == '/' %}
  <title>Home | {{ site.title }}</title>
{% else %}
  <title>{{ title }} | {{ site.title }}</title>
{% endif %}
```

**Comment by michelle-rago** [comment]
> This is the correct fix! I noticed the homepage doesn't have a title so it ends up getting " | Federal website standards" as its title. I can fix that if you want. It'll be something like:
> 
> ```
> {% if permalink == '/' %}
>   <title>Home | {{ site.title }}</title>
> {% else %}
>   <title>{{ title }} | {{ site.title }}</title>
> {% endif %}
> ```
> 
> We could also just allow the homepage to use `{{site.title}}` by itself.

Great! Yes, please do fix the home page title. I'd like the home page title to be "Federal website standards for executive branch federal agencies" - can we just pop that in there and then not include site.title for the home page? I want more of a descriptive title here because this is one of our pending standards. Let me know if you think this is a bad idea.

**Comment by caleywoods** [comment]
> > This is the correct fix! I noticed the homepage doesn't have a title so it ends up getting " | Federal website standards" as its title. I can fix that if you want. It'll be something like:
> > ```
> > {% if permalink == '/' %}
> >   <title>Home | {{ site.title }}</title>
> > {% else %}
> >   <title>{{ title }} | {{ site.title }}</title>
> > {% endif %}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We could also just allow the homepage to use `{{site.title}}` by itself.
> 
> Great! Yes, please do fix the home page title. I'd like the home page title to be "Federal website standards for executive branch federal agencies" - can we just pop that in there and then not include site.title for the home page? I want more of a descriptive title here because this is one of our pending standards. Let me know if you think this is a bad idea.

Yes we can make the homepage title just be "Federal website standards for executive branch federal agencies".

**Comment by caleywoods** [comment]
:shipit:

**Pull request merged**
