### PR TITLE
Enable search.gov

### PR DESCRIPTION
**Pull request by michelle-rago**
- Add search.gov handle
- Add access key
- Add results page

### CODE REVIEW

**Review by caleywoods — APPROVED** [review]
:shipit:

**Comment by michelle-rago** [comment]
@caleywoods I think we still need to add code for the search form, but I'm not sure. Looking through documentation at https://search.gov/get-started/site-launch-guide.html.

**Comment by michelle-rago** [comment]
@caleywoods Can you take a look at this? I'm not sure what else we need to do to see results.

**Comment by caleywoods** [comment]
> @caleywoods Can you take a look at this? I'm not sure what else we need to do to see results.

Yes I'll take a look today.

**Pull request merged**
