### PR TITLE
Add the hero component to the homepage

### LINKED ISSUE #186: Add a simple hero to home page
Specs:
background: USA color blue 40
text: white
button: dark primary

[mockup here](https://drive.google.com/drive/folders/1-Fll_xRL8QlDYVKS75VBaecCr2UrZ7it)

### PR DESCRIPTION
**Pull request by caleywoods**
## Context
Fixes #186 

## Description
This adds the hero component to the base layout if the current page permalink is `/` so that the hero only renders on the homepage. There's an included overrides file to make the style fit the mockup.

## How to verify this change
[Visit the preview URL](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/preview/gsa-tts/federal-website-standards/caley/hero/) and observe the hero component below the nav menu on the homepage.

### CODE REVIEW

**Comment by caleywoods** [comment]
@evoeges @michelle-rago There's some extra padding below the hero before the content starts that comes from `usa-section` setting `4rem`. Thoughts on overriding that to maybe `2rem` or removing `usa-section`?

**Comment by caleywoods** [comment]
@michelle-rago Are we good for this one to be merged?

**Comment by michelle-rago** [comment]
> @michelle-rago Are we good for this one to be merged?

Let's wait for @evoeges to have a look. Thanks!

**Review by evoeges — APPROVED** [review]
Caley and I reviewed together, looks good to me.

**Pull request merged**
