### PR TITLE
Cleanup items

### PR DESCRIPTION
**Pull request by caleywoods**
## Context
* Remove `outline-1px` on the Draft component that was missed from #194 
* Remove the white `box-shadow` property from the USWDS usa-step indicator component that appears on each standard page

## How to verify this change
Pick one standard in each of our current three statuses (pending, research, draft) and verify that the white outline that was previously around each step number is now gone. On the site search standard (draft status) the 1 pixel outline should be gone as well.

* [HTML Page title](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/preview/gsa-tts/federal-website-standards/caley/cleanup/standards/html-page-title/) (Pending status)
* [Contact](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/preview/gsa-tts/federal-website-standards/caley/cleanup/standards/contact-research/) (Research status)
* [Site search](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/preview/gsa-tts/federal-website-standards/caley/cleanup/standards/site-search-draft/) (Draft status)

Federal government banner, Meta page description, and content timeliness indicator don't need to be checked because they all share a status with one of the standards linked above.

### CODE REVIEW

**Comment by caleywoods** [comment]
@evoeges This PR has the change that removes the white `box-shadow` on the USWDS step component that we discussed in the morning meeting.

**Comment by michelle-rago** [comment]
I'm still not seeing the gray box on the search standard. @caleywoods 
image

**Comment by michelle-rago** [comment]
> I'm still not seeing the gray box on the search standard. @caleywoods image

Oh, sorry! I think this ticket wasn't meant to address this issue.

**Review by michelle-rago — APPROVED** [review]

**Comment by caleywoods** [comment]
@michelle-rago I fixed the draft component background just now. See [site search](https://federalist-142078a8-f654-4daa-8f73-db9770b3ec7a.sites.pages.cloud.gov/preview/gsa-tts/federal-website-standards/caley/cleanup/standards/site-search-draft/)

**Pull request merged**
